// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package InputShare

import "strconv"

type EventType int8

const (
	EventTypeKeyDown EventType = 0
	EventTypeKeyUp   EventType = 1
)

var EnumNamesEventType = map[EventType]string{
	EventTypeKeyDown: "KeyDown",
	EventTypeKeyUp:   "KeyUp",
}

var EnumValuesEventType = map[string]EventType{
	"KeyDown": EventTypeKeyDown,
	"KeyUp":   EventTypeKeyUp,
}

func (v EventType) String() string {
	if s, ok := EnumNamesEventType[v]; ok {
		return s
	}
	return "EventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
