// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package InputShare

import "strconv"

type EventType int8

const (
	EventTypeKeyDown        EventType = 0
	EventTypeKeyUp          EventType = 1
	EventTypeClipboard      EventType = 2
	EventTypePlatformQuery  EventType = 3
	EventTypePlatformInfo   EventType = 4
	EventTypePing           EventType = 5
	EventTypePong           EventType = 6
)

var EnumNamesEventType = map[EventType]string{
	EventTypeKeyDown:        "KeyDown",
	EventTypeKeyUp:          "KeyUp",
	EventTypeClipboard:      "Clipboard",
	EventTypePlatformQuery:  "PlatformQuery",
	EventTypePlatformInfo:   "PlatformInfo",
	EventTypePing:           "Ping",
	EventTypePong:           "Pong",
}

var EnumValuesEventType = map[string]EventType{
	"KeyDown":        EventTypeKeyDown,
	"KeyUp":          EventTypeKeyUp,
	"Clipboard":      EventTypeClipboard,
	"PlatformQuery":  EventTypePlatformQuery,
	"PlatformInfo":   EventTypePlatformInfo,
	"Ping":           EventTypePing,
	"Pong":           EventTypePong,
}

func (v EventType) String() string {
	if s, ok := EnumNamesEventType[v]; ok {
		return s
	}
	return "EventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
