// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package InputShare

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsKeyEvent(buf []byte, offset flatbuffers.UOffsetT) *KeyEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeyEvent(buf []byte, offset flatbuffers.UOffsetT) *KeyEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KeyEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyEvent) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyEvent) Modifiers(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *KeyEvent) ModifiersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func KeyEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func KeyEventAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func KeyEventAddModifiers(builder *flatbuffers.Builder, modifiers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(modifiers), 0)
}
func KeyEventStartModifiersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func KeyEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
