// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package InputShare

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MouseEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsMouseEvent(buf []byte, offset flatbuffers.UOffsetT) *MouseEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MouseEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishMouseEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMouseEvent(buf []byte, offset flatbuffers.UOffsetT) *MouseEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MouseEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMouseEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MouseEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MouseEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MouseEvent) X() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MouseEvent) MutateX(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *MouseEvent) Y() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MouseEvent) MutateY(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *MouseEvent) Button() MouseButton {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return MouseButton(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MouseEvent) MutateButton(n MouseButton) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *MouseEvent) IsRelative() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *MouseEvent) MutateIsRelative(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *MouseEvent) ScrollDx() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MouseEvent) MutateScrollDx(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *MouseEvent) ScrollDy() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MouseEvent) MutateScrollDy(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func MouseEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func MouseEventAddX(builder *flatbuffers.Builder, x int32) {
	builder.PrependInt32Slot(0, x, 0)
}
func MouseEventAddY(builder *flatbuffers.Builder, y int32) {
	builder.PrependInt32Slot(1, y, 0)
}
func MouseEventAddButton(builder *flatbuffers.Builder, button MouseButton) {
	builder.PrependInt8Slot(2, int8(button), 0)
}
func MouseEventAddIsRelative(builder *flatbuffers.Builder, isRelative bool) {
	builder.PrependBoolSlot(3, isRelative, false)
}
func MouseEventAddScrollDx(builder *flatbuffers.Builder, scrollDx int32) {
	builder.PrependInt32Slot(4, scrollDx, 0)
}
func MouseEventAddScrollDy(builder *flatbuffers.Builder, scrollDy int32) {
	builder.PrependInt32Slot(5, scrollDy, 0)
}
func MouseEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
