// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package InputShare

import "strconv"

type MouseButton int8

const (
	MouseButtonLeft   MouseButton = 0
	MouseButtonRight  MouseButton = 1
	MouseButtonMiddle MouseButton = 2
)

var EnumNamesMouseButton = map[MouseButton]string{
	MouseButtonLeft:   "Left",
	MouseButtonRight:  "Right",
	MouseButtonMiddle: "Middle",
}

var EnumValuesMouseButton = map[string]MouseButton{
	"Left":   MouseButtonLeft,
	"Right":  MouseButtonRight,
	"Middle": MouseButtonMiddle,
}

func (v MouseButton) String() string {
	if s, ok := EnumNamesMouseButton[v]; ok {
		return s
	}
	return "MouseButton(" + strconv.FormatInt(int64(v), 10) + ")"
}
