// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package InputShare

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ScreenInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsScreenInfo(buf []byte, offset flatbuffers.UOffsetT) *ScreenInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ScreenInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishScreenInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsScreenInfo(buf []byte, offset flatbuffers.UOffsetT) *ScreenInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ScreenInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedScreenInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ScreenInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ScreenInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ScreenInfo) Width() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScreenInfo) MutateWidth(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *ScreenInfo) Height() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScreenInfo) MutateHeight(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *ScreenInfo) ScaleFactor() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ScreenInfo) MutateScaleFactor(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *ScreenInfo) Platform() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ScreenInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ScreenInfoAddWidth(builder *flatbuffers.Builder, width int32) {
	builder.PrependInt32Slot(0, width, 0)
}
func ScreenInfoAddHeight(builder *flatbuffers.Builder, height int32) {
	builder.PrependInt32Slot(1, height, 0)
}
func ScreenInfoAddScaleFactor(builder *flatbuffers.Builder, scaleFactor float32) {
	builder.PrependFloat32Slot(2, scaleFactor, 0.0)
}
func ScreenInfoAddPlatform(builder *flatbuffers.Builder, platform flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(platform), 0)
}
func ScreenInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
